wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      - 5
      4: 3.8.8
      5: 0.10.33
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 16
cfg:
  desc: null
  value: ..\SIIM_FISABIO_RSNA_COVID_19_Detection\yolov5\models\yolov5s.yaml
data:
  desc: null
  value: ..\SIIM_FISABIO_RSNA_COVID_19_Detection\yolov5\data\data.yaml
data_dict:
  desc: null
  value:
    names:
    - none
    - opacity
    nc: 2
    train: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\temp/covid/images/train
    val: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\temp/covid/images/valid
device:
  desc: null
  value: cpu
entity:
  desc: null
  value: poi
epochs:
  desc: null
  value: 10
evolve:
  desc: null
  value: false
hyp:
  desc: null
  value:
    names:
    - none
    - opacity
    nc: 2
    train: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\temp/covid/images/train
    val: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\temp/covid/images/valid
img_size:
  desc: null
  value:
  - 256
  - 256
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
opt:
  desc: null
  value:
    batch_size: 16
    bbox_interval: 2
    cfg: ..\SIIM_FISABIO_RSNA_COVID_19_Detection\yolov5\models\yolov5s.yaml
    data: ..\SIIM_FISABIO_RSNA_COVID_19_Detection\yolov5\data\data.yaml
    device: cpu
    entity: poi
    epochs: 10
    evolve: false
    hyp:
      names:
      - none
      - opacity
      nc: 2
      train: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\temp/covid/images/train
      val: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\temp/covid/images/valid
    img_size:
    - 256
    - 256
    nosave: false
    notest: false
    project: kaggle-siim-covid
    resume: false
    save_dir: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\save
    save_period: 1
    single_cls: false
    upload_dataset: false
    weights: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\/siim-covid19-detection/yolov5s.pt
    workers: 8
project:
  desc: null
  value: kaggle-siim-covid
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\save
save_period:
  desc: null
  value: 1
single_cls:
  desc: null
  value: false
weights:
  desc: null
  value: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\/siim-covid19-detection/yolov5s.pt
workers:
  desc: null
  value: 8
