wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      - 5
      4: 3.8.8
      5: 0.10.33
      8:
      - 1
      - 3
      - 5
data_dict:
  desc: null
  value:
    names:
    - none
    - opacity
    nc: 2
    train: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\tmp/covid/images/train
    val: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\tmp/covid/images/valid
opt:
  desc: null
  value:
    adam: false
    artifact_alias: latest
    batch: 16
    batch_size: 16
    bbox_interval: -1
    bucket: ''
    cache_images: false
    cfg: ''
    data: ..\SIIM_FISABIO_RSNA_COVID_19_Detection\yolov5\data\data.yaml
    device: ''
    entity: null
    epochs: 10
    evolve: null
    exist_ok: false
    hyp:
      anchor_t: 4.0
      box: 0.05
      cls: 0.5
      cls_pw: 1.0
      copy_paste: 0.0
      degrees: 0.0
      fl_gamma: 0.0
      fliplr: 0.5
      flipud: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      iou_t: 0.2
      lr0: 0.01
      lrf: 0.2
      mixup: 0.0
      momentum: 0.937
      mosaic: 1.0
      obj: 1.0
      obj_pw: 1.0
      perspective: 0.0
      scale: 0.5
      shear: 0.0
      translate: 0.1
      warmup_bias_lr: 0.1
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      weight_decay: 0.0005
    image_weights: false
    img: 256
    img_size:
    - 640
    - 640
    label_smoothing: 0.0
    linear_lr: false
    local_rank: -1
    multi_scale: false
    name: exp
    noautoanchor: false
    nosave: false
    notest: false
    project: runs/train
    quad: false
    rect: false
    resume: false
    save_dir: runs\train\exp12
    save_period: -1
    single_cls: false
    sync_bn: false
    upload_dataset: false
    weights: yolov5s.pt
    workers: 8
