weights: yolov5s.pt
cfg: ''
data: ..\SIIM_FISABIO_RSNA_COVID_19_Detection\yolov5\data\data.yaml
hyp: .\yolov5\data\hyps\hyp.scratch.yaml
epochs: 10
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: null
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
img: 256
batch: 16
save_dir: runs\train\exp9
