wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.8.8
      5: 0.10.33
      8:
      - 1
      - 3
      - 5
data_dict:
  desc: null
  value:
    names:
    - none
    - opacity
    nc: 2
    train: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\tmp/covid/images/train
    val: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\tmp/covid/images/valid
opt:
  desc: null
  value:
    artifact_alias: latest
    batch_size: 16
    bbox_interval: 2
    cfg: ..\SIIM_FISABIO_RSNA_COVID_19_Detection\yolov5\models\yolov5s.yaml
    data: ..\SIIM_FISABIO_RSNA_COVID_19_Detection\yolov5\data\data.yaml
    device: cpu
    entity: poi
    epochs: 10
    evolve: false
    hyp:
      anchor_t:
      - 1
      - 2.0
      - 8.0
      anchors:
      - 2
      - 2.0
      - 10.0
      box:
      - 1
      - 0.02
      - 0.2
      cls:
      - 1
      - 0.2
      - 4.0
      cls_pw:
      - 1
      - 0.5
      - 2.0
      copy_paste:
      - 1
      - 0.0
      - 1.0
      degrees:
      - 1
      - 0.0
      - 45.0
      fl_gamma:
      - 0
      - 0.0
      - 2.0
      fliplr:
      - 0
      - 0.0
      - 1.0
      flipud:
      - 1
      - 0.0
      - 1.0
      hsv_h:
      - 1
      - 0.0
      - 0.1
      hsv_s:
      - 1
      - 0.0
      - 0.9
      hsv_v:
      - 1
      - 0.0
      - 0.9
      iou_t:
      - 0
      - 0.1
      - 0.7
      lr0:
      - 1
      - 1.0e-05
      - 0.1
      lrf:
      - 1
      - 0.01
      - 1.0
      mixup:
      - 1
      - 0.0
      - 1.0
      momentum:
      - 0.3
      - 0.6
      - 0.98
      mosaic:
      - 1
      - 0.0
      - 1.0
      obj:
      - 1
      - 0.2
      - 4.0
      obj_pw:
      - 1
      - 0.5
      - 2.0
      perspective:
      - 0
      - 0.0
      - 0.001
      scale:
      - 1
      - 0.0
      - 0.9
      shear:
      - 1
      - 0.0
      - 10.0
      translate:
      - 1
      - 0.0
      - 0.9
      warmup_bias_lr:
      - 1
      - 0.0
      - 0.2
      warmup_epochs:
      - 1
      - 0.0
      - 5.0
      warmup_momentum:
      - 1
      - 0.0
      - 0.95
      weight_decay:
      - 1
      - 0.0
      - 0.001
    img_size:
    - 256
    - 256
    nosave: false
    notest: false
    project: kaggle-siim-covid
    resume: false
    save_dir: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\save
    save_period: 1
    single_cls: false
    upload_dataset: false
    weights: E:\train_and_test_data\SIIM_FISABIO_RSNA_COVID_19_Detection\\/siim-covid19-detection/yolov5s.pt
    workers: 8
